from enum import Enum
from typing import Any, TypeVar, assert_never

from adaptix import Retort

from maxo.bot.methods import (
    AnswerOnCallback,
    DeleteChat,
    DeleteMessage,
    EditBotInfo,
    EditChat,
    EditMessage,
    GetAdmins,
    GetChat,
    GetChatByLink,
    GetChats,
    GetMembers,
    GetMembership,
    GetMessageById,
    GetMessages,
    GetMyInfo,
    GetPinnedMessage,
    GetSubscriptions,
    GetUpdates,
    GetUploadUrl,
    GetVideoAttachmentDetails,
    LeaveChat,
    PinMessage,
    RemoveMember,
    SendAction,
    SendMessage,
    SetAdmins,
    Subscribe,
    UnpinMessage,
    Unsubscribe,
    UploadMedia,
)
from maxo.types import (
    Attachment,
    AttachmentPayload,
    AttachmentRequest,
    Attachments,
    AudioAttachment,
    AudioAttachmentRequest,
    BotCommand,
    BotInfo,
    Button,
    Callback,
    CallbackAnswer,
    CallbackButton,
    Chat,
    ChatAdmin,
    ChatAdminsList,
    ChatButton,
    ChatList,
    ChatMember,
    ChatMembersList,
    CommandObject,
    ContactAttachment,
    ContactAttachmentPayload,
    ContactAttachmentRequest,
    ContactAttachmentRequestPayload,
    DataAttachment,
    EmphasizedMarkupElement,
    FileAttachment,
    FileAttachmentPayload,
    FileAttachmentRequest,
    GetPinnedMessageResult,
    GetSubscriptionsResult,
    HeadingMarkupElement,
    HighlightedMarkupElement,
    Image,
    InlineButtons,
    InlineKeyboardAttachment,
    InlineKeyboardAttachmentRequest,
    InlineKeyboardAttachmentRequestPayload,
    Keyboard,
    LinkButton,
    LinkMarkupElement,
    LinkedMessage,
    LocationAttachment,
    LocationAttachmentRequest,
    MarkupElements,
    MaxoType,
    MediaAttachmentPayload,
    Message,
    MessageBody,
    MessageButton,
    MessageList,
    MonospacedMarkupElements,
    NewMessage,
    NewMessageBody,
    NewMessageLink,
    OpenAppButton,
    PhotoAttachment,
    PhotoAttachmentPayload,
    PhotoAttachmentRequest,
    PhotoAttachmentRequestPayload,
    PhotoToken,
    PhotoTokens,
    PinMessageBody,
    Recipient,
    ReplyButton,
    ReplyButtons,
    ReplyKeyboardAttachment,
    ReplyKeyboardAttachmentRequest,
    RequestContactButton,
    RequestGeoLocationButton,
    SendContactButton,
    SendGeoLocationButton,
    SendMessageButton,
    SendMessageResult,
    ShareAttachment,
    ShareAttachmentPayload,
    ShareAttachmentRequest,
    SimpleQueryResult,
    StickerAttachment,
    StickerAttachmentPayload,
    StickerAttachmentRequest,
    StickerAttachmentRequestPayload,
    StrikethroughMarkupElement,
    StrongMarkupElement,
    Subscription,
    UnderlineMarkupElement,
    UpdateContext,
    UpdateList,
    UploadEndpoint,
    User,
    UserMentionMarkupElement,
    UserWithPhoto,
    VideoAttachment,
    VideoAttachmentDetails,
    VideoAttachmentRequest,
    VideoThumbnail,
    VideoUrls,
)


class WarmingUpType(Enum):
    METHOD = "method"
    TYPES = "types"


_types = (
    Attachment,
    AttachmentPayload,
    AttachmentRequest,
    Attachments,
    AudioAttachment,
    AudioAttachmentRequest,
    MaxoType,
    BotCommand,
    BotInfo,
    Button,
    InlineButtons,
    ReplyButtons,
    Callback,
    CallbackAnswer,
    CallbackButton,
    Chat,
    ChatAdmin,
    ChatAdminsList,
    ChatButton,
    ChatList,
    ChatMember,
    ChatMembersList,
    CommandObject,
    ContactAttachment,
    ContactAttachmentPayload,
    ContactAttachmentRequest,
    ContactAttachmentRequestPayload,
    DataAttachment,
    FileAttachment,
    FileAttachmentPayload,
    FileAttachmentRequest,
    GetPinnedMessageResult,
    GetSubscriptionsResult,
    Image,
    InlineKeyboardAttachment,
    InlineKeyboardAttachmentRequest,
    InlineKeyboardAttachmentRequestPayload,
    Keyboard,
    LinkButton,
    LinkedMessage,
    LocationAttachment,
    LocationAttachmentRequest,
    EmphasizedMarkupElement,
    HeadingMarkupElement,
    HighlightedMarkupElement,
    LinkMarkupElement,
    MarkupElements,
    MonospacedMarkupElements,
    StrikethroughMarkupElement,
    StrongMarkupElement,
    UnderlineMarkupElement,
    UserMentionMarkupElement,
    MediaAttachmentPayload,
    Message,
    MessageBody,
    MessageButton,
    MessageList,
    NewMessage,
    NewMessageBody,
    NewMessageLink,
    OpenAppButton,
    PhotoAttachment,
    PhotoAttachmentPayload,
    PhotoAttachmentRequest,
    PhotoAttachmentRequestPayload,
    PhotoToken,
    PhotoTokens,
    PinMessageBody,
    Recipient,
    ReplyButton,
    ReplyKeyboardAttachment,
    ReplyKeyboardAttachmentRequest,
    RequestContactButton,
    RequestGeoLocationButton,
    SendContactButton,
    SendGeoLocationButton,
    SendMessageButton,
    SendMessageResult,
    ShareAttachment,
    ShareAttachmentPayload,
    ShareAttachmentRequest,
    SimpleQueryResult,
    StickerAttachment,
    StickerAttachmentPayload,
    StickerAttachmentRequest,
    StickerAttachmentRequestPayload,
    Subscription,
    UpdateContext,
    UpdateList,
    UploadEndpoint,
    User,
    UserWithPhoto,
    VideoAttachment,
    VideoAttachmentDetails,
    VideoAttachmentRequest,
    VideoThumbnail,
    VideoUrls,
)


_methods = (
    AnswerOnCallback,
    DeleteChat,
    DeleteMessage,
    EditBotInfo,
    EditChat,
    EditMessage,
    GetAdmins,
    GetChat,
    GetChatByLink,
    GetChats,
    GetMembers,
    GetMembership,
    GetMessageById,
    GetMessages,
    GetMyInfo,
    GetPinnedMessage,
    GetSubscriptions,
    GetUpdates,
    GetUploadUrl,
    GetVideoAttachmentDetails,
    LeaveChat,
    PinMessage,
    RemoveMember,
    SendAction,
    SendMessage,
    SetAdmins,
    Subscribe,
    UnpinMessage,
    Unsubscribe,
    UploadMedia,
)

_RetortT = TypeVar("_RetortT", bound=Retort)


def warming_up_retort(
    retort: _RetortT,
    warming_up: WarmingUpType | None = None,
) -> _RetortT:
    if warming_up is None:
        return retort

    types: tuple[Any, ...]
    if warming_up is WarmingUpType.METHOD:
        types = _methods
        retort_method = retort.get_dumper
    elif warming_up is WarmingUpType.TYPES:
        types = _types
        retort_method = retort.get_loader
    else:
        assert_never(warming_up)

    for tp in types:
        retort_method(tp)

    return retort
